### ISSUE TITLE
账号信息获取失败

### ISSUE THREAD

**Issue by jiang3231634** [srcrs/UnicomTask-docker#16]
虽然知道问题代码，但还是不知道怎么去改。。。docker部署的，都是根据主页代码进行的。。。有大佬能看看怎么解决吗？
错误如下：
ERROR:账号信息获取失败错误，原因为: Expecting property name enclosed in double quotes: line 8 column 9 (char 290)
[2021-07-22 06:30:11,134]:ERROR:1.请检查是否在Secrets添加了账号信息，以及添加的位置是否正确。
[2021-07-22 06:30:11,134]:ERROR:2.填写之前，是否在网站验证过Json格式的正确性。
Traceback (most recent call last):
  File "/root/UnicomTask-docker/index.py", line 241, in readJson
    users = json.load(fp)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 9 (char 290)

Traceback (most recent call last):
  File "/root/UnicomTask-docker/index.py", line 462, in <module>
    main_handler("","")
  File "/root/UnicomTask-docker/index.py", line 422, in main_handler
    for user in users:
TypeError: 'NoneType' object is not iterable

**Comment by Dellear** [comment]
映射/config目录到宿主机，然后把代码库里的config里的两个文件放到那个目录里，修改一下账号信息就可以了，执行命令需要使用crontab.list的命令

**Comment by srcrs** [comment]
> 虽然知道问题代码，但还是不知道怎么去改。。。docker部署的，都是根据主页代码进行的。。。有大佬能看看怎么解决吗？
> 
> 错误如下：
> 
> ERROR:账号信息获取失败错误，原因为: Expecting property name enclosed in double quotes: line 8 column 9 (char 290)
> 
> [2021-07-22 06:30:11,134]:ERROR:1.请检查是否在Secrets添加了账号信息，以及添加的位置是否正确。
> 
> [2021-07-22 06:30:11,134]:ERROR:2.填写之前，是否在网站验证过Json格式的正确性。
> 
> Traceback (most recent call last):
> 
>   File "/root/UnicomTask-docker/index.py", line 241, in readJson
> 
>     users = json.load(fp)
> 
>   File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
> 
>     return loads(fp.read(),
> 
>   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
> 
>     return _default_decoder.decode(s)
> 
>   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
> 
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> 
>   File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
> 
>     obj, end = self.scan_once(s, idx)
> 
> json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 9 (char 290)
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/root/UnicomTask-docker/index.py", line 462, in <module>
> 
>     main_handler("","")
> 
>   File "/root/UnicomTask-docker/index.py", line 422, in main_handler
> 
>     for user in users:
> 
> TypeError: 'NoneType' object is not iterable

config.json映射出现了问题

**Comment by faustining** [comment]
对不起，我也不会，我是粘贴，你在哪看到的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月16日(周一) 中午1:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [srcrs/unicom-task] 账号信息获取失败 (#16)




  
虽然知道问题代码，但还是不知道怎么去改。。。docker部署的，都是根据主页代码进行的。。。有大佬能看看怎么解决吗？
 
错误如下：
 
ERROR:账号信息获取失败错误，原因为: Expecting property name enclosed in double quotes: line 8 column 9 (char 290)
 
Traceback (most recent call last):
 
File "/root/UnicomTask-docker/index.py", line 241, in readJson
 users = json.load(fp)  
File "/usr/local/lib/python3.9/json/init.py", line 293, in load
 return loads(fp.read(),  
File "/usr/local/lib/python3.9/json/init.py", line 346, in loads
 return _default_decoder.decode(s)  
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
 obj, end = self.raw_decode(s, idx=_w(s, 0).end())  
File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
 obj, end = self.scan_once(s, idx)  
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 9 (char 290)
 
Traceback (most recent call last):
 
File "/root/UnicomTask-docker/index.py", line 462, in 
 main_handler("","")  
File "/root/UnicomTask-docker/index.py", line 422, in main_handler
 for user in users:  
TypeError: 'NoneType' object is not iterable
  
config.json映射出现了问题
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by srcrs** [comment]
> 虽然知道问题代码，但还是不知道怎么去改。。。docker部署的，都是根据主页代码进行的。。。有大佬能看看怎么解决吗？
> 
> 错误如下：
> 
> ERROR:账号信息获取失败错误，原因为: Expecting property name enclosed in double quotes: line 8 column 9 (char 290)
> 
> [2021-07-22 06:30:11,134]:ERROR:1.请检查是否在Secrets添加了账号信息，以及添加的位置是否正确。
> 
> [2021-07-22 06:30:11,134]:ERROR:2.填写之前，是否在网站验证过Json格式的正确性。
> 
> Traceback (most recent call last):
> 
>   File "/root/UnicomTask-docker/index.py", line 241, in readJson
> 
>     users = json.load(fp)
> 
>   File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
> 
>     return loads(fp.read(),
> 
>   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
> 
>     return _default_decoder.decode(s)
> 
>   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
> 
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> 
>   File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
> 
>     obj, end = self.scan_once(s, idx)
> 
> json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 8 column 9 (char 290)
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/root/UnicomTask-docker/index.py", line 462, in <module>
> 
>     main_handler("","")
> 
>   File "/root/UnicomTask-docker/index.py", line 422, in main_handler
> 
>     for user in users:
> 
> TypeError: 'NoneType' object is not iterable

一般是config.json映射失败导致

**Comment by srcrs** [comment]
检查下 -v后面config.json对应的路径是否正确
