### ISSUE TITLE
[天天抽奖]：错误，原因为：'Rsptype'

### ISSUE THREAD

**Issue by jianrry** [srcrs/UnicomTask-docker#7]
```
Traceback (most recent call last):

  File "/var/user/index.py", line 114, in luckDraw_task

    if res['Rsptype'] == '6666':

KeyError: 'Rsptype'

```

我在config.json中删掉了一行

```
 "lotteryNum": "抽奖次数（选填，不填请删除此行）",
```

不知道是不是这一行导致的

**Comment by srcrs** [comment]
> ```
> Traceback (most recent call last):
> 
>   File "/var/user/index.py", line 114, in luckDraw_task
> 
>     if res['Rsptype'] == '6666':
> 
> KeyError: 'Rsptype'
> ```
> 
> 我在config.json中删掉了一行
> 
> ```
>  "lotteryNum": "抽奖次数（选填，不填请删除此行）",
> ```
> 
> 不知道是不是这一行导致的

是云函数还是docker？

**Comment by jianrry** [comment]
> > ```
> > Traceback (most recent call last):
> > 
> >   File "/var/user/index.py", line 114, in luckDraw_task
> > 
> >     if res['Rsptype'] == '6666':
> > 
> > KeyError: 'Rsptype'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我在config.json中删掉了一行
> > ```
> >  "lotteryNum": "抽奖次数（选填，不填请删除此行）",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不知道是不是这一行导致的
> 
> 是云函数还是docker？

腾讯云函数

**Comment by tengqian** [comment]
我也出现这个问题，云函数，配置只保留了`username`,`password`,`appId`,`email`
